event_one_hours = int(input())
event_one_minutes = int(input())
event_one_seconds = int(input())
event_two_hours = int(input())
event_two_minutes = int(input())
event_two_seconds = int(input())
print(((event_two_hours - event_one_hours) * 3600)
      + ((event_two_minutes - event_one_minutes) * 60)
      + event_two_seconds - event_one_seconds)
